### PR TITLE
.NET Core project

### PR DESCRIPTION
**Pull request by aKzenT**
Hey,

this pull request adds a .NET core project file as well as some minor changes to allow a .NET core compatible build.

Kindly review it and let me know if there is anything further I can do to move this forward.

See also this issue on codeplex: https://51degrees.codeplex.com/workitem/10961

Thanks!

### CODE REVIEW

**Comment by Steve51D** [comment]
Hi @aKzenT , I'm a developer at 51 Degrees.
Firstly, thank you for taking the time to put this together and pass it back to us.

I have been doing some prototyping internally to determine the steps required in migrating the code base to .NET Core as well as any architectural changes that would make sense to be included at the same time.

I've had a brief look at your pull request and I'm not 100% convinced it is really targeting .NET Core. In my own investigations, System.Drawing was not available in Core and there were no plans to add it. (from what I understand, this is because of headaches in making it cross platform) So I'm not sure why the calls to that API are still functioning.

This is one clear example but there are other areas that show the same inconsistencies.
Can you shed any light on this?

Finally, I can't say anything too concrete at this stage but we are currently looking towards at least a beta version of the .NET Core API in early 2017

Thanks,
Steve.

**Comment by aKzenT** [comment]
Hey Steve,

thank you for your feedback. It's great that you are already working on .NET core.

The .net core project is based on the files used in the SQL Server project, not the complete list of classes from the .net project. I explained this idea in the issue at codeplex, but did not explain it here. Sorry for that!

So the code only contains the necessary classes to load the device data files and allowing to parse a User Agent string to get the device information. It does not contain code tied to any particular version of MVC and therefore does not depend on System.Drawing, etc.

I actually think it would be nice to have like a core assembly with these classes and having additional assemblies targetting MVC, MVC Core, etc. with the optimizations. This would make it easy for you to target specific frameworks and at the same time allow users to only load what they needed without any bloat. For this pull request I wanted to keep the changes small though. Let me know what you think about this idea as well.

You might be confused that Visual Studio shows all .cs files in the project. This is because in xproj files, all files in the directory are always "included". There is no concept of include/exclude. You can however specify which files are to be used during compilation, which I did in the project.json file. I expect this behaviour to change with the release of VS2017, when the project system is based on MSBuild and .csproj again, so I wouldn't spent too much time on this annoyance.

Regards,
Thomas

**Comment by Steve51D** [comment]
Hi Thomas,

Apologies for the slow feedback, festive period and all that!
We are actually planning to move to a more granular package approach when we release the .NETCore nuget packages so looks like we're on the same wavelength there.

Thanks for the clarification re. the xproj file. The fact that it shows all files but doesn't use them seems unnecessarily confusing!

I currently have some higher priority work that I need to get finished off but once that's done I'll be working on changes to the device detection API including the .NETCore project. As part of that we'll be testing these changes in more detail.

Regards,
Steve.

**Comment by Steve51D** [comment]
Hi Thomas, 

Just letting you know that we'll be going with this approach for the initial .NETCore release. The intention is to follow that in the future with a 'native' .NET Standard implementation that will also address some more fundamental design choices in the API.

To allow more control over the repositories, what we normally do in these situations is to pull the changes to our internal develop branch and make tweaks, etc before pushing them back out to public master as part of a release.
We then link the pull request you've made to that release but don't actually complete it. 

Hope that's okay with you, any problems, let me know.
Many thanks for your assistance with this.

Regards,
Steve.

**Comment by Steve51D** [comment]
Hi Thomas, 

This change is now in the public repository as part of release 3.2.16.2
Many thanks for you assistance with it.

Regards,
Steve.

**Comment by manigandham** [comment]
@Steve51D - can we get this uploaded to [Nuget](https://www.nuget.org/packages/51Degrees.mobi-core/) to use in our projects?

**Comment by Steve51D** [comment]
@manigandham 

Yes, that's the intention. Unfortunately, we're having some trouble with the package dependencies on Visual Studio 2015. (It works fine on 2017). We have been in discussion with NuGet support and they have asked us to raise it as an issue [here](https://github.com/NuGet/Home/issues/5130).

As soon as those problems are resolved we'll be uploading the package to NuGet.

Regards,
Steve.

**Comment by Steve51D** [comment]
@manigandham 

Hi, We have now released a beta version of the NuGet package containing the .NET Core / .NET Standard build.
To get it you'll need to tick the 'Show prerelease' checkbox in NuGet Package Manager.

This package appears to work fine in Visual Studio 2017, in 2015, you'll need to manually add the dependencies after adding the package. (you don't need to do this for .NET Framework projects, only .NET Core/Standard)

**Comment by JauernigIT** [comment]
Can you give some hints how to use with ASP.NET Core? Is there some middleware that can be plugged-in to the pipeline?

**Comment by Steve51D** [comment]
Our current .NET Core project is simply the .NET 4 project with some parts removed. As such it does not have any middleware or any other .NET Core specific components.

We are working on a native .NET Core library. However, this currently has no firm release date (certainly won't be until after .NET Core 2 is available). 
In the meantime, I would suggest middleware doing something like this:

```
public async Task Invoke(HttpContext context)
{
	// Get Headers
	var headers = GetRequiredHeaders(context);
	// Perform the match
	Match match = _provider.Match(headers);
	// Store match in HttpContext for use further down the pipeline
	context.Items.Add(Constants.HTTPCONTEXT_MATCH, match);
}

private NameValueCollection GetRequiredHeaders(HttpContext context)
{
	// Convert IHeaderDictionary to NameValueCollection
	NameValueCollection headerCollection = null;
	headerCollection = context.Request.Headers as NameValueCollection;
	if (headerCollection == null)
	{
		headerCollection = new NameValueCollection();
		foreach (var header in context.Request.Headers)
		{
			headerCollection.Add(header.Key, header.Value);
		}
	}
	return headerCollection;
}
```

_provider is a normal 51Degrees provider. I would recommend creating it and the associated dataset in your Startup.ConfigureServices and then supply it to the middleware via DI in the constructor.

**Pull request closed without merging**
