### PR TITLE
Updated C# usage example

### PR DESCRIPTION
**Pull request by Chris45215**
The syntax Request.Browser["IsMobile"] does not compile when I tested it. Also, the class of Request needs to be clarified, as C# has both HttpRequest and HttpWebRequest.

### CODE REVIEW

**Comment by JoshGrew51D** [comment]
Hi Chris - Would you be able to send over the errors you are getting when trying to compile with the original syntax?

**Comment by 51Degrees-Products** [comment]
Use Github.com for communication. Also remember everything you write is in public.

Sent from mobile. Excuse brevity.

________________________________

**Review by JoshGrew51D — CHANGES_REQUESTED** [review]
Thanks for your suggestion. We're happy to include the code comment. However, Request.Browser[] returns a String so you will need to convert it to Boolean before performing a Boolean operation. This may be why it failed to compile.

**Comment by JoshGrew51D** [comment]
Closing for now due to no response. Please do re-open if you wish to submit the changes requested.

**Pull request closed without merging**
